### ISSUE TITLE
Export uses title instead of code

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/wn-redirect-plugin#12]
When exporting the table, the column names are actual names and not the DB code name.
![image](https://user-images.githubusercontent.com/89913092/209144679-17e03854-1695-4a99-bb7d-cf82e31608d0.png)
I would expect it to be (for example) `match_type`, and not `Match Type [match_type] (Allowed values: exact, placeholders, regex)`

**Comment by LukeTowers** [comment]
Why would you expect that? It's using the column names from the list which are translatable.

**Comment by AIC-BV** [comment]
The column names are really big in the excel file, but I guess it doesn't really matter
